{% set version = "3.1.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lintr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lintr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lintr/lintr_{{ version }}.tar.gz
  sha256: 35d379999b0c2f0955a963027b9fb6ad03456ea58a57ee57dc2e5a0e10505377

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-backports
    - r-codetools
    - r-crayon
    - r-cyclocomp
    - r-digest
    - r-glue
    - r-jsonlite
    - r-knitr
    - r-rex
    - r-xml2 >=1.0.0
    - r-xmlparsedata >=1.0.5
  run:
    - r-base
    - r-backports
    - r-codetools
    - r-crayon
    - r-cyclocomp
    - r-digest
    - r-glue
    - r-jsonlite
    - r-knitr
    - r-rex
    - r-xml2 >=1.0.0
    - r-xmlparsedata >=1.0.5

test:
  commands:
    - $R -e "library('lintr')"           # [not win]
    - "\"%R%\" -e \"library('lintr')\""  # [win]

about:
  home: https://lintr.r-lib.org
  dev_url: https://github.com/jimhester/lintr
  license: MIT
  summary: Checks adherence to a given style, syntax errors and possible semantic issues.  Supports on the fly checking of R code edited with 'RStudio IDE', 'Emacs', 'Vim', 'Sublime Text' and 'Atom'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - Adrianzo
