{% set version = '1.0.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lintr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lintr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lintr/lintr_{{ version }}.tar.gz
  sha256: bd226d2248716d8a7748703e15e490d2a738fd714a7586f9d8ad8937027e9a6e

build:
  merge_build_host: True  # [win]
  number: 1000
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-codetools
    - r-crayon
    - r-digest
    - r-httr
    - r-igraph
    - r-jsonlite
    - r-knitr
    - r-rex
    - r-rstudioapi >=0.2
    - r-stringdist
    - r-testthat
  run:
    - r-base
    - r-codetools
    - r-crayon
    - r-digest
    - r-httr
    - r-igraph
    - r-jsonlite
    - r-knitr
    - r-rex
    - r-rstudioapi >=0.2
    - r-stringdist
    - r-testthat

test:
  commands:
    - $R -e "library('lintr')"           # [not win]
    - "\"%R%\" -e \"library('lintr')\""  # [win]

about:
  home: https://github.com/jimhester/lintr
  license: MIT
  summary: Checks adherence to a given style, syntax errors and possible semantic issues.  Supports
    on the fly checking of R code edited with 'RStudio IDE', 'Emacs', 'Vim', 'Sublime
    Text' and 'Atom'.
  license_family: MIT
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - Adrianzo
    - dbast

# Package: lintr
# Title: A 'Linter' for R Code
# Version: 1.0.3
# Authors@R: person("Jim", "Hester", email = "james.f.hester@gmail.com", role = c("aut", "cre"))
# URL: https://github.com/jimhester/lintr
# BugReports: https://github.com/jimhester/lintr/issues
# Description: Checks adherence to a given style, syntax errors and possible semantic issues.  Supports on the fly checking of R code edited with 'RStudio IDE', 'Emacs', 'Vim', 'Sublime Text' and 'Atom'.
# Depends: R (>= 3.1.1)
# Imports: rex, crayon, codetools, stringdist, testthat, digest, igraph, rstudioapi (>= 0.2), httr, jsonlite, knitr, stats, utils
# Suggests: rmarkdown, mockery
# License: MIT + file LICENSE
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-11-08 16:39:01 UTC; jhester
# Author: Jim Hester [aut, cre]
# Maintainer: Jim Hester <james.f.hester@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-11-08 17:10:10 UTC
