{% set version = '1.0.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lintr
  version: {{ version|replace("-", "_") }}

source:
  fn: lintr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/lintr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lintr/lintr_{{ version }}.tar.gz
  sha256: f61eb02fe102f30aedf60b8f526659623eeb87c1c520de49e45ab05645748692

build:
  merge_build_host: True  # [win]
  number: 2

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-codetools
    - r-crayon
    - r-digest
    - r-httr
    - r-igraph
    - r-jsonlite
    - r-knitr
    - r-rex
    - r-rstudioapi >=0.2
    - r-stringdist
    - r-testthat

  run:
    - r-base
    - r-codetools
    - r-crayon
    - r-digest
    - r-httr
    - r-igraph
    - r-jsonlite
    - r-knitr
    - r-rex
    - r-rstudioapi >=0.2
    - r-stringdist
    - r-testthat

test:
  commands:
    - $R -e "library('lintr')"           # [not win]
    - "\"%R%\" -e \"library('lintr')\""  # [win]

about:
  home: https://github.com/jimhester/lintr
  license: MIT
  summary: Checks adherence to a given style, syntax errors and possible semantic issues.  Supports
    on the fly checking of R code edited with 'RStudio IDE', 'Emacs', 'Vim', 'Sublime
    Text' and 'Atom'.
  license_family: MIT
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\MIT'      # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - Adrianzo
    - dbast
