appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: FMBnImLeCy8oM294CaegFyeDDLDoAOQevM/dvl2A3kjpmENYpMi8y43YiOR7P7OpgKY9S5J1cEpCh6yHVqaWWAPPKHphpOD3z70DpExnCP5i/AJDhC1Mm78iiuqFPhhweq0H/kDlwI0bZqoExU1Q1LG1XHBlOEEQEkTBva96jjNX3NEvXVdTUX5BPdcrxhVrCPA1o2ZripZ1tEXRbPh0AW84sRrPKQkJlpfi+CwNaF77Aw78JN73UwzFsdly+kG+xmYM5NxYndODYEOAChrupB7FGlD802Fp6c7Kq5yb418d9k7xymCGd1+9AOYavsztnL9kiRz5EkAWWdFf6eijgpJk3OUCS7MhSDP0y5ysO1JEkOeMk8tDeqjtbjlWyrt7B7lXLZklQUuATsTn3wytf6YaCkuIhjBHWDlKYNhbaIbz0ChGtWPgbVqhQ51628a8mWXIs0vkmkWtoYp1oZJMx3gUbyKpPTX5tDyQWGaNA7SK/ZbS+po4m33k1D5HhD1wOZpbinhOruJbzFm3FJRKRFxDy+uVZz2sSEXlC6M93iz/yVV6Vi9TmNjGZ0F9O2j0TrDdfWUHCKTPOD7mdxwtV7SCbAOUl7VNY32dG9bbwrb2kL1Yc9f1AKjSBky89MenbpISvGQJJ7Zh4i4SEtk2Si0zK39YMtG8TIFLb4a669Y=}
bot:
  automerge: true
